<a href="https://colab.research.google.com/github/sarithamiryala/DeepLearning/blob/main/pytorch1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

2.5.1+cu121


In [3]:
if torch.cuda.is_available():
    print("cuda is available")
else:
    print("cuda is not available")

cuda is available


# Creating a Tensor

In [6]:
# using empty
a = torch.empty((2,3))

In [7]:
a

tensor([[-7.6400e-14,  3.3093e-41,  0.0000e+00],
        [ 1.4013e-45,  8.9683e-44,  0.0000e+00]])

In [8]:
type(a)

torch.Tensor

In [9]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [10]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [15]:
# using rand
torch.rand(2,3)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

In [14]:
#manual seed
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [21]:
# using tensor

t1 = torch.tensor([[2,3,4],
                   [5,6,7],
                   []])
t1

tensor([[2, 3, 4],
        [5, 6, 7]])

In [22]:
t1.shape

torch.Size([2, 3])

In [23]:
#otherways


#arrange
print("using arange-->", torch.arange(0,10,2))

#linspace
print("using linspace-->", torch.linspace(0,10,5))


using arange--> tensor([0, 2, 4, 6, 8])
using linspace--> tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])


In [24]:
# using eye
print("using eye",torch.eye(5))

using eye tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [25]:
#using full
print("using full",torch.full((2,3),4))

using full tensor([[4, 4, 4],
        [4, 4, 4]])
