<a href="https://colab.research.google.com/github/sarithamiryala/DeepLearning/blob/main/pytorch_training_pipeline_using_nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
# create model class

import torch
import torch.nn as nn

class Model(nn.Module):
  def __init__(self,num_features):

    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [22]:
#create dataset
features = torch.rand(10,5)

#create model
model = Model(features.shape[1])

#call model for forward pass
model(features)

tensor([[0.3329],
        [0.3202],
        [0.3392],
        [0.3457],
        [0.2888],
        [0.3408],
        [0.3059],
        [0.3586],
        [0.2963],
        [0.3722]], grad_fn=<SigmoidBackward0>)

In [23]:
# show model weights
model.linear.weight

Parameter containing:
tensor([[-0.1028, -0.0505,  0.0478, -0.3535, -0.1423]], requires_grad=True)

In [24]:
model.linear.bias

Parameter containing:
tensor([-0.4214], requires_grad=True)

In [25]:
!pip install torchinfo

In [26]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [27]:
# create model class

import torch
import torch.nn as nn

class Model(nn.Module):
  def __init__(self,num_features):

    super().__init__()
    self.linear1 = nn.Linear(num_features,3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)

    return out

In [28]:
#create dataset
features = torch.rand(10,5)

#create model
model = Model(features.shape[1])

#call model for forward pass
model(features)

tensor([[0.4213],
        [0.4459],
        [0.4505],
        [0.4466],
        [0.4455],
        [0.4054],
        [0.4339],
        [0.4325],
        [0.4050],
        [0.4326]], grad_fn=<SigmoidBackward0>)

In [29]:
model.linear1.weight

Parameter containing:
tensor([[ 0.1527, -0.0425,  0.3342,  0.2808, -0.2449],
        [ 0.3917,  0.0344,  0.3592,  0.3822,  0.2505],
        [ 0.0180,  0.1936,  0.0946, -0.4107,  0.1429]], requires_grad=True)

In [30]:
model.linear1.bias

Parameter containing:
tensor([-0.3301, -0.3847, -0.3060], requires_grad=True)

In [31]:
model.linear2.weight

Parameter containing:
tensor([[-0.3324, -0.2779, -0.4995]], requires_grad=True)

In [32]:
model.linear2.bias

Parameter containing:
tensor([-0.1585], requires_grad=True)

In [33]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [34]:
# sequential container

# create model class

import torch
import torch.nn as nn

class Model(nn.Module):
  def __init__(self,num_features):

    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )

  def forward(self,features):
    out = self.network(features)

    return out

In [35]:
#create dataset
features = torch.rand(10,5)

#create model
model = Model(features.shape[1])

#call model for forward pass
model(features)

tensor([[0.5324],
        [0.5453],
        [0.5263],
        [0.5580],
        [0.5321],
        [0.5576],
        [0.5349],
        [0.4898],
        [0.5037],
        [0.5110]], grad_fn=<SigmoidBackward0>)