<a href="https://colab.research.google.com/github/sarithamiryala/DeepLearning/blob/main/TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf


In [ ]:
tf.__version__

'2.17.0'

## Tensor Constant

In [ ]:
const = tf.constant(10)

In [ ]:
const

<tf.Tensor: shape=(), dtype=int32, numpy=10>

JAX : Built on Numpy but it supports CUDA

In [ ]:
# for Specific datatype

const = tf.constant(43,dtype=tf.float32)

In [ ]:
const

<tf.Tensor: shape=(), dtype=float32, numpy=43.0>

In [ ]:
const.numpy()

43.0

In [ ]:
const_mat = tf.constant([[1,3],[4,5]],dtype=tf.float32)

In [ ]:
const_mat

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 3.],
       [4., 5.]], dtype=float32)>

In [ ]:
const_mat.shape

TensorShape([2, 2])

In [ ]:
const_mat.dtype

tf.float32

In [ ]:
const_mat[0][1]

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

In [ ]:
const_mat[0][0]=32

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

#Commonly used methods

In [ ]:
tf.ones(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
-1*tf.ones(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-1., -1., -1.],
       [-1., -1., -1.]], dtype=float32)>

In [ ]:
tf.zeros(shape=(2,4))

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

# ADD Operation

In [ ]:
const1 = tf.constant([[1,2,3],[4,5,6]])
const2 = tf.constant([[2,3,5],[4,5,6]])

In [ ]:
const1+const2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 3,  5,  8],
       [ 8, 10, 12]], dtype=int32)>

In [ ]:
tf.add(const1,const2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 3,  5,  8],
       [ 8, 10, 12]], dtype=int32)>

In [ ]:
tf.random.normal(shape=(2,2),mean=0,stddev=1.0)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.8985935 , 0.6278246 ],
       [0.43701023, 0.08419178]], dtype=float32)>

In [ ]:
tf.random.uniform(shape=(2,2),minval=0,maxval=20)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 9.159328 , 14.276554 ],
       [10.480428 ,  5.5599236]], dtype=float32)>

#Variables

In [ ]:
var1 = tf.Variable([[1,2,3],[4,5,6]])
var1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [ ]:
var1[0][0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [ ]:
var2 = tf.Variable(43)
var2

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=43>

In [ ]:
var2.assign(23)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=23>

In [ ]:
var2

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=23>

In [ ]:
var1.assign([[5,2,3],[4,5,6]])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[5, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [ ]:
var1[1,1].assign(22)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[ 5,  2,  3],
       [ 4, 22,  6]], dtype=int32)>

# Reshaping Operation

In [ ]:
tensor = tf.Variable([[1,2,3],[4,5,6]])

In [ ]:
tensor.shape

TensorShape([2, 3])

In [ ]:
tf.reshape(tensor,shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [ ]:
tf.reshape(tensor,shape=(1,6))

<tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[1, 2, 3, 4, 5, 6]], dtype=int32)>

In [ ]:
tf.reshape(tensor,shape=(6,1))

<tf.Tensor: shape=(6, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]], dtype=int32)>

# Other mathematical Operations

In [ ]:
var1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[ 5,  2,  3],
       [ 4, 22,  6]], dtype=int32)>

In [ ]:
tf.square(var1)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 25,   4,   9],
       [ 16, 484,  36]], dtype=int32)>

In [ ]:
tf.pow(var1,2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 25,   4,   9],
       [ 16, 484,  36]], dtype=int32)>

## Broadcasting in TF

In [ ]:
tensor

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [ ]:
scaler = 4

tensor*scaler

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 4,  8, 12],
       [16, 20, 24]], dtype=int32)>

In [ ]:
tensor+scaler

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 5,  6,  7],
       [ 8,  9, 10]], dtype=int32)>

## Matrix Multiplication

In [ ]:
mat_u = tf.Variable([[1,2,3],[4,5,6]])
mat_u.shape

TensorShape([2, 3])

In [ ]:
mat_v =tf.Variable([[1,2],[3,4],[5,6]])
mat_v.shape

TensorShape([3, 2])

In [ ]:
tf.matmul(mat_u,mat_v)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 28],
       [49, 64]], dtype=int32)>

In [ ]:
mat_u @ mat_v

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 28],
       [49, 64]], dtype=int32)>

In [ ]:
# dot product
mat_u * tf.transpose(mat_v)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  6, 15],
       [ 8, 20, 36]], dtype=int32)>

#Casting  Method ( if we want to change the data type)

In [ ]:
mat_u.dtype

tf.int32

In [ ]:
tf.cast(mat_u,dtype=tf.int16)

<tf.Tensor: shape=(2, 3), dtype=int16, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int16)>

# casting can be used to save spaces or memory (quantization) or rounding off

In [ ]:
# 34.343434
#34.34

# Ragged tensor

In [ ]:
#nested variable length arrays  (for example in text the length are diferent )

In [ ]:
ragged = tf.ragged.constant([[1,2,3,4,5,6],[1],[135,1]])

In [ ]:
ragged.shape

TensorShape([3, None])

In [ ]:
ragged[0]

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>

In [ ]:
ragged[0].shape

TensorShape([6])

In [ ]:
ragged[1].shape

TensorShape([1])